<a href="https://colab.research.google.com/github/Mjdiazri/Code7Days/blob/main/Ejercicio_promt_python_dataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Acceso a los datos**

A continuacion se presentara dos opciones para acceder a los datos:
Opcion 1: Utilizar la funcion pd.read_json para crear el dataframe
Opcion 2: Realizar el acceso desde la api y crear dataframe con request y funcion pd.Dataframe

In [1]:
#busca recolectar y acceder a los datos del archivo que están en formato JSON. Es importante dejar todos los datos de manera accesible, evitando estructuras que recuerden a un archivo JSON, como diccionarios.

#Opcion 1: Con url fija
url_franquicias = 'https://gist.githubusercontent.com/ahcamachod/68eede222bdf1ba0ca413d529e800e7c/raw/576b0f3856467817df0fcf041d4a0787579917b0/ventas_franquicia.json'

In [2]:
import pandas as pd
import numpy as np

In [15]:
#busca recolectar y acceder a los datos del archivo que están en formato JSON. Es importante dejar todos los datos de manera accesible, evitando estructuras que recuerden a un archivo JSON, como diccionarios.

#Opcion 2: Desde api

import requests

#Solicitud a la api
response = requests.get(url_franquicias)
#Convirtiendo respuesta de json a objeto python
data = response.json()
#Creando dataframe
datafra= pd.DataFrame(data)
datafra

,ID_tienda,ventas,tienda
0,OUT431,"{'ventas_por_dia': None, 'ventas_tienda': 8222...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
1,OUT738,"{'ventas_por_dia': None, 'ventas_tienda': 1032...","{'tamano_tienda': 'medio', 'cliente_por_dia': ..."
2,OUT426,"{'ventas_por_dia': None, 'ventas_tienda': 5548...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
3,OUT948,"{'ventas_por_dia': None, 'ventas_tienda': 9641...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
4,OUT139,"{'ventas_por_dia': None, 'ventas_tienda': 5680...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
...,...,...,...
893,OUT206,"{'ventas_por_dia': None, 'ventas_tienda': 8787...","{'tamano_tienda': 'medio', 'cliente_por_dia': ..."
894,OUT370,"{'ventas_por_dia': None, 'ventas_tienda': 2941...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
895,OUT960,"{'ventas_por_dia': None, 'ventas_tienda': 5736...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
896,OUT535,"{'ventas_por_dia': None, 'ventas_tienda': 6158...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
897,OUT202,"{'ventas_por_dia': None, 'ventas_tienda': 9541...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."

In [4]:
#Continuacion proceso, igual dos opciones

uf = pd.read_json(url_franquicias)
uf

,ID_tienda,ventas,tienda
0,OUT431,"{'ventas_por_dia': None, 'ventas_tienda': 8222...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
1,OUT738,"{'ventas_por_dia': None, 'ventas_tienda': 1032...","{'tamano_tienda': 'medio', 'cliente_por_dia': ..."
2,OUT426,"{'ventas_por_dia': None, 'ventas_tienda': 5548...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
3,OUT948,"{'ventas_por_dia': None, 'ventas_tienda': 9641...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
4,OUT139,"{'ventas_por_dia': None, 'ventas_tienda': 5680...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
...,...,...,...
893,OUT206,"{'ventas_por_dia': None, 'ventas_tienda': 8787...","{'tamano_tienda': 'medio', 'cliente_por_dia': ..."
894,OUT370,"{'ventas_por_dia': None, 'ventas_tienda': 2941...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
895,OUT960,"{'ventas_por_dia': None, 'ventas_tienda': 5736...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
896,OUT535,"{'ventas_por_dia': None, 'ventas_tienda': 6158...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
897,OUT202,"{'ventas_por_dia': None, 'ventas_tienda': 9541...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."

In [6]:
#Se tienen dos diccionarios: ventas y tienda

#Normalizacion Ventas
ventas_uf= pd.json_normalize(uf['ventas'])
ventas_uf

     ventas_por_dia  ventas_tienda
0               NaN   82220.053714
1               NaN  103231.728424
2               NaN   55487.996318
3               NaN   96417.999686
4               NaN   56809.025487
..              ...            ...
893             NaN   87875.440154
894             NaN   29410.047183
895             NaN   57362.867709
896             NaN   61585.737092
897             NaN   95416.455607

[898 rows x 2 columns]

In [7]:
#Normalizacion tienda

tienda_uf = pd.json_normalize(uf['tienda'])
tienda_uf

    tamano_tienda  cliente_por_dia  items_disponibles
0         pequeno            330.0               1968
1           medio            310.0               2189
2         pequeno            870.0               1736
3         Pequeno           1560.0               1099
4         Pequeno             10.0               1516
..            ...              ...                ...
893         medio            810.0               2031
894       Pequeno            780.0               1439
895       Pequeno            660.0               1510
896       pequeno            990.0               1836
897       Pequeno           1170.0               1500

[898 rows x 3 columns]

In [9]:
#Unificacion dataframe

uf_union = pd.concat([uf.drop(['ventas', 'tienda'],axis=1), ventas_uf, tienda_uf], axis=1)

In [11]:
uf_union

,ID_tienda,ventas_por_dia,ventas_tienda,tamano_tienda,cliente_por_dia,items_disponibles
0,OUT431,NaN,82220.053714,pequeno,330.0,1968
1,OUT738,NaN,103231.728424,medio,310.0,2189
2,OUT426,NaN,55487.996318,pequeno,870.0,1736
3,OUT948,NaN,96417.999686,Pequeno,1560.0,1099
4,OUT139,NaN,56809.025487,Pequeno,10.0,1516
...,...,...,...,...,...,...
893,OUT206,NaN,87875.440154,medio,810.0,2031
894,OUT370,NaN,29410.047183,Pequeno,780.0,1439
895,OUT960,NaN,57362.867709,Pequeno,660.0,1510
896,OUT535,NaN,61585.737092,pequeno,990.0,1836
897,OUT202,NaN,95416.455607,Pequeno,1170.0,1500

**Exploracion del dataframe**

In [16]:
uf_union.head()

,ID_tienda,ventas_por_dia,ventas_tienda,tamano_tienda,cliente_por_dia,items_disponibles
0,OUT431,NaN,82220.053714,pequeno,330.0,1968
1,OUT738,NaN,103231.728424,medio,310.0,2189
2,OUT426,NaN,55487.996318,pequeno,870.0,1736
3,OUT948,NaN,96417.999686,Pequeno,1560.0,1099
4,OUT139,NaN,56809.025487,Pequeno,10.0,1516

In [17]:
uf_union.tail()

,ID_tienda,ventas_por_dia,ventas_tienda,tamano_tienda,cliente_por_dia,items_disponibles
893,OUT206,NaN,87875.440154,medio,810.0,2031
894,OUT370,NaN,29410.047183,Pequeno,780.0,1439
895,OUT960,NaN,57362.867709,Pequeno,660.0,1510
896,OUT535,NaN,61585.737092,pequeno,990.0,1836
897,OUT202,NaN,95416.455607,Pequeno,1170.0,1500

In [18]:
uf_union.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_tienda          898 non-null    object
 1   ventas_por_dia     1 non-null      float64
 2   ventas_tienda      898 non-null    float64
 3   tamano_tienda      878 non-null    object
 4   cliente_por_dia    880 non-null    float64
 5   items_disponibles  898 non-null    int64
dtypes: float64(3), int64(1), object(2)
memory usage: 42.2+ KB

In [19]:
uf_union.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_tienda          898 non-null    object
 1   ventas_por_dia     1 non-null      float64
 2   ventas_tienda      898 non-null    float64
 3   tamano_tienda      878 non-null    object
 4   cliente_por_dia    880 non-null    float64
 5   items_disponibles  898 non-null    int64
dtypes: float64(3), int64(1), object(2)
memory usage: 138.4 KB

In [20]:
uf_union.describe()

       ventas_por_dia  ventas_tienda  cliente_por_dia  items_disponibles
count         1.00000     898.000000       880.000000         898.000000
mean       4294.64706   71071.894236       786.443182        1781.561247
std               NaN   22143.481947       267.038209         299.716498
min        4294.64706   19371.958539        10.000000         932.000000
25%        4294.64706   54510.922957       600.000000        1574.500000
50%        4294.64706   69228.128375       780.000000        1773.000000
75%        4294.64706   86119.754844       970.000000        1982.000000
max        4294.64706  152897.262005      1560.000000        2667.000000

In [21]:
uf_union.shape

(898, 6)

In [22]:
uf_union.isnull().sum()

ID_tienda              0
ventas_por_dia       897
ventas_tienda          0
tamano_tienda         20
cliente_por_dia       18
items_disponibles      0
dtype: int64

In [23]:
uf_union.duplicated().sum()

np.int64(2)

In [24]:
uf_union.nunique()

ID_tienda            896
ventas_por_dia         1
ventas_tienda        896
tamano_tienda          3
cliente_por_dia      130
items_disponibles    616
dtype: int64